import js from "@eslint/js";
import prettier from "eslint-config-prettier";

export default [
  js.configs.recommended,
  prettier,
  {
    files: ["public/js/**/*.js", "public/app.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        document: "readonly",
        window: "readonly",
        navigator: "readonly",
        screen: "readonly",
        sessionStorage: "readonly",
        localStorage: "readonly",
        MutationObserver: "readonly",
        fetch: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        URL: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        HTMLElement: "readonly",
        HTMLCanvasElement: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        AbortController: "readonly",
        URLSearchParams: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        IntersectionObserver: "readonly",
        Image: "readonly",
        alert: "readonly",
        location: "readonly",
        history: "readonly",
        performance: "readonly",
        L: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
      }],
      "no-console": "off",
    },
  },
  {
    files: ["public/__tests__/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        document: "readonly",
        window: "readonly",
        navigator: "readonly",
        fetch: "readonly",
        /* Response gehoert wie fetch zur Web-Schnittstelle und wird in
           queue.test.js zum Nachstellen von Serverantworten gebraucht. Ohne
           diesen Eintrag scheitert `npm run lint:frontend` — und damit der
           Pflicht-Check test-frontend (Audit 2026-08-10, OPS-001). */
        Response: "readonly",
        /* Wird zum Nachstellen eines abgebrochenen fetch gebraucht (BUG-003). */
        DOMException: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        HTMLElement: "readonly",
        HTMLCanvasElement: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        AbortController: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        Image: "readonly",
        alert: "readonly",
        location: "readonly",
        history: "readonly",
        performance: "readonly",
        L: "readonly",
        test: "readonly",
        describe: "readonly",
        it: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        vi: "readonly",
        sessionStorage: "readonly",
        localStorage: "readonly",
        MutationObserver: "readonly",
        /* Für den Test des Modus-Speichers: `localStorage` als Gegenprobe
           (die Wahl darf dort NICHT landen), `Storage` zum Nachstellen eines
           defekten Speichers wie im privaten Safari-Modus. */
        localStorage: "readonly",
        MutationObserver: "readonly",
        Storage: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
      }],
      "no-console": "off",
    },
  },
  {
    ignores: ["node_modules/", "functions/", "public/lib/", "public/fonts/"],
  },
];
